# Generated by Django 2.2.5 on 2019-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_photo_link', models.CharField(blank=True, max_length=255, null=True)),
                ('view_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
