# Generated by Django 2.2.5 on 2019-10-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191027_1128'),
        ('api', '0002_auto_20191026_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
