# Generated by Django 2.2.5 on 2019-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191004_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aphorism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
