# Generated by Django 2.2.5 on 2019-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='extra',
        ),
        migrations.AddField(
            model_name='course',
            name='evening_super_pray',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fasting',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='night_pray',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='super_pray',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='epistle',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='jawshan',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pray',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='quran',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
