# Generated by Django 2.2.5 on 2019-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20191117_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='epistle',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='evenint_super_pray',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='fasting',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='jawshan',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='night_pray',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='pray',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='quran',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='super_pray',
            field=models.IntegerField(default=-1),
        ),
    ]
