# Generated by Django 2.2.5 on 2019-11-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20191117_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='evenint_super_pray',
            new_name='evening_super_pray',
        ),
    ]
