# Generated by Django 2.2.5 on 2019-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20191118_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
